# Define variables for project ID, image name, and tag.
# Customize these values as needed.
substitutions:
  _PROJECT_ID: 'vibrant-petal-406618'  # Replace with your actual project ID.
  _IMAGE_NAME: 'us-docker.pkg.dev/vibrant-petal-406618/testa-artf/itito'
  _TAG_NAME: '0.0.1'
  _REGION: 'us-central1'  # Replace with your preferred region.
  _SERVICE_NAME: 'my-cloud-run-service-2'  # Replace with your preferred Cloud Run service name.

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_NAME}:${_TAG_NAME}', '.']

# Push the Docker image to Google Container Registry.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}:${_TAG_NAME}']
# Deploy to Cloud Run.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image=${_IMAGE_NAME}:${_TAG_NAME}'
  - '--platform=managed'
  - '--region=${_REGION}'
  - '--allow-unauthenticated'  # Optional: Remove this line if you don't want to allow unauthenticated access.

images:
- '${_IMAGE_NAME}:${_TAG_NAME}'  # Reference the dynamic image name and tag.
